### ISSUE TITLE
Unable to upgrade to Apache SSHD 1.1.1

### ISSUE THREAD

**Issue by kvbkvm** [ggrandes/sftpserver#10]
I have some errors when I try to compile with sshd 1.0.0 instead of 0.14.0

http://mvnrepository.com/artifact/org.apache.sshd/sshd-core/1.0.0

To reproduce : 

replace 0.14.0 by 1.0.0 in pom.xml

**Comment by ggrandes** [comment]
Version 1.1.1 works better; 1.0.0 of sshd-core is buggy, with errors like this:

    sftp> 
    buffer_get_ret: trying to get more bytes 4 than in buffer 0
    buffer_get_int: buffer error

**Comment by ggrandes** [comment]
done at [a257aeb]
