### ISSUE TITLE
download file, it have a  EOF Exception

### ISSUE THREAD

**Issue by garyfub** [ggrandes/sftpserver#11]
download file, it have a  EOF Exception . it  run in windows 7 environment，  jdk 1.8 .

Server$CustomSftpSubsystemFactory$1:3292 - doSendStatus(ServerSessionImpl[test@/127.0.0.1:55462])[id=383] SSH_FXP_STATUS (substatus=SSH_FX_EOF, lang=, msg=java.io.EOFException: Unable to read 16384 bytes from offset=12340403 of 7b6d575567751ee2088f69f846ae28e6)

**Comment by ggrandes** [comment]
Bug is located in MINA-SSHD: [SSHD-725](https://issues.apache.org/jira/browse/SSHD-725)

**Comment by ggrandes** [comment]
You can try version [1.2.1](https://github.com/ggrandes/sftpserver/tree/v1.2.1)

**Comment by garyfub** [comment]
Thank you !






At 2017-08-07 18:53:55, "G.Grandes" <notifications@github.com> wrote:


You can try version 1.2.1
