### ISSUE TITLE
Generate hostkey with shh-rsa instead of ssh-dss

### ISSUE THREAD

**Issue by a-schild** [ggrandes/sftpserver#12]
Currently the default implementation generates a host key with ssh-dss key type.
Most ssh clients don't any longer support the ssh-dss type, better would be to generate the server key with a ssh-rsa or better key.

There the corresponding log entry when trying to connect with open ssh client 7.4 distributed with Debian 9
```
2017-10-17 18:38:29,707 WARN org.apache.sshd.server.session.ServerSessionImpl exceptionCaught(ServerSessionImpl[null@/0:0:0:0:0:0:0:1:56314])[state=Opened] IllegalStateException: Unable to negotiate key exc
hange for server host key algorithms (client: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-
rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa / server: ssh-dss)

```

Here the openssh page mentioning this:
[https://www.openssh.com/legacy.html]

OpenSSH 7.0 and greater similarly disable the ssh-dss (DSA) public key algorithm. It too is weak and we recommend against its use.

**Comment by a-schild** [comment]
Workarround is to stop the ssh daemon and create a hostkey with your linux sssj-keygen

**Comment by ggrandes** [comment]
Thanks for the reports!
