### ISSUE TITLE
Can I use this project if my project based on Java 1.6?

### ISSUE THREAD

**Issue by xlhtc007** [ggrandes/sftpserver#14]
My project is build on Java 1.6. Can I integrate this sftpserver in my project? Is it easy for me to implement an sftpserver based on Java1.6 according to your project?

**Comment by a-schild** [comment]
You can try to download it and change the source level in the pom.xml to 1.6 and see if it compiles.

**Comment by ggrandes** [comment]
sftpserver 1.1.1 was 1.6 compatible. After upgrade sshd-core to 1.2 [700fd4c4cf4c9fc9a3e8bfbeeba8a9cdcf105a9c] java 1.7 is required.
