### ISSUE TITLE
How to get started tutorial..?

### ISSUE THREAD

**Issue by wordlessly** [ggrandes/sftpserver#16]
Hi,

I downloaded the latest release and played around with sftpd.sh start or pwd. I don't manage to get it running. Somethings is not right. I seems to look for files in /opt/sftpd/... and then fails.

Maybe there is a step-by-step guide showing how it is done?

**Comment by a-schild** [comment]
What platform are you running on?

**Comment by wordlessly** [comment]
Linux

**Comment by ggrandes** [comment]
##### Quick-start Guide

###### In console 1
```bash
export SFTPD_HOME=/tmp/sftpd
mkdir -pm775 $SFTPD_HOME
cd $SFTPD_HOME
unzip -o /tmp/sftpserver-X.X.X-bin.zip 
${SFTPD_HOME}/bin/sftpd.sh run sampleconf
```
###### In console 2
```bash
# sftp -P 22222 test@localhost
Password authentication
Password: clean-unencripted-password
Connected to localhost.
sftp> pwd
Remote working directory: /
sftp> quit
```

**Comment by xugongwei1996** [comment]
hello:
I am using your project, but there is a problem in the process of using it. The connection time is too short. Is there any way to modify the timeout? I found the configuration file and every directory, but no configuration parameters were found

thanks,please

**Comment by leopitris** [comment]
I'd like to set up the sftpd user is not chrooted. What chages should I do in order to accomplish this.
